all: false
dir: "{{.InterfaceDir}}"
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  snippets.adelh.dev/app/internal/db:
    interfaces:
      Store:
        config:
          dir: app/internal/db/mocks
          filename: store_mock.go
          pkgname: mocks
  snippets.adelh.dev/app/internal/db/sqlc:
    interfaces:
      Querier:
        config:
          dir: app/internal/db/mocks
          filename: qierier_mock.go
          pkgname: mocks
