// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Snippet struct {
	ID           int32          `db:"id"`
	PublicID     string         `db:"public_id"`
	Title        sql.NullString `db:"title"`
	CreatedAt    time.Time      `db:"created_at"`
	ExpiresAt    sql.NullTime   `db:"expires_at"`
	PasswordHash sql.NullString `db:"password_hash"`
	EditToken    string         `db:"edit_token"`
	ViewCount    int32          `db:"view_count"`
	LastEditedAt sql.NullTime   `db:"last_edited_at"`
}

type SnippetContent struct {
	SnippetID        int32  `db:"snippet_id"`
	ContentType      string `db:"content_type"`
	EncryptedContent []byte `db:"encrypted_content"`
}
