// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Creates a new snippet
	CreateSnippet(ctx context.Context, arg CreateSnippetParams) (CreateSnippetRow, error)
	// Deletes all snippets that have expired
	DeleteExpiredSnippets(ctx context.Context) (int64, error)
	// Deletes a snippet by id
	DeleteSnippetById(ctx context.Context, id int32) (int64, error)
	// Retrieves a snippet by its public ID
	GetSnippetByPublicID(ctx context.Context, publicID string) (GetSnippetByPublicIDRow, error)
	// Increments the view count for a snippet
	IncrementSnippetViewCount(ctx context.Context, id int32) (int32, error)
	// Lists recently created snippets (for admin purposes)
	ListRecentSnippets(ctx context.Context, limit int32) ([]ListRecentSnippetsRow, error)
	// Updates an existing snippet by ID
	UpdateSnippet(ctx context.Context, arg UpdateSnippetParams) (UpdateSnippetRow, error)
	// Updates the content of a snippet
	UpdateSnippetContent(ctx context.Context, arg UpdateSnippetContentParams) error
}

var _ Querier = (*Queries)(nil)
